Docker + workflows update

diff --git a/wordpress/Dockerfile b/wordpress/Dockerfile
--- a/wordpress/Dockerfile
+++ b/wordpress/Dockerfile
@@ -2,32 +2,140 @@ ARG BUILD_FROM=ghcr.io/hassio-addons/base:17.2.1
 # hadolint ignore=DL3006
 FROM ${BUILD_FROM}
 
-# Create directory for apache2 to store PID file
-RUN mkdir /run/apache2
+# Environment variables
+ENV \
+    CARGO_NET_GIT_FETCH_WITH_CLI=true \
+    HOME="/root" \
+    LANG="C.UTF-8" \
+    PIP_BREAK_SYSTEM_PACKAGES=1 \
+    PYTHONUNBUFFERED=1
 
-RUN apk add --no-cache bash curl less vim nginx ca-certificates git tzdata zip \
-    libmcrypt-dev zlib-dev gmp-dev \
-    freetype-dev libjpeg-turbo-dev libpng-dev \
-    php81-fpm php81-json php81-zlib php81-xml php81-xmlwriter php81-simplexml php81-pdo php81-phar php81-openssl \
-    php81-pdo_mysql php81-mysqli php81-session \
-    php81-gd php81-iconv php81-gmp php81-zip \
-    php81-curl php81-opcache php81-ctype php81-apcu \
-    php81-intl php81-bcmath php81-dom php81-mbstring php81-xmlreader mysql-client curl && apk add -u musl && \
-    rm -rf /var/cache/apk/*
+# Install required dependencies
+RUN apk add --no-cache \
+    apache2 \
+    php8 \
+    php8-apache2 \
+    php8-mysqli \
+    php8-json \
+    php8-session \
+    php8-mbstring \
+    php8-xml \
+    php8-gd \
+    php8-curl \
+    php8-zip \
+    php8-opcache \
+    php8-pdo_mysql \
+    php8-tokenizer \
+    php8-ctype \
+    php8-simplexml \
+    libpng-dev \
+    freetype-dev \
+    libjpeg-turbo-dev \
+    oniguruma-dev \
+    libxml2-dev \
+    zip \
+    unzip \
+    tzdata \
+    shadow \
+    gcc \
+    g++ \
+    make \
+    autoconf \
+    dpkg-dev \
+    pkgconf \
+    libc-dev \
+    libstdc++ \
+    bash \
+    coreutils \
+    curl \
+    git \
+    wget \
+    openssl \
+    ca-certificates \
+    ghostscript \
+    libavif-dev \
+    libfreetype6-dev \
+    libicu-dev \
+    libjpeg-dev \
+    libmagickwand-dev \
+    libpng-dev \
+    libwebp-dev \
+    libzip-dev
 
-RUN sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' /etc/php81/php.ini && \
-    sed -i 's/expose_php = On/expose_php = Off/g' /etc/php81/php.ini && \
-    sed -i "s/nginx:x:100:101:nginx:\/var\/lib\/nginx:\/sbin\/nologin/nginx:x:100:101:nginx:\/usr:\/bin\/bash/g" /etc/passwd && \
-    sed -i "s/nginx:x:100:101:nginx:\/var\/lib\/nginx:\/sbin\/nologin/nginx:x:100:101:nginx:\/usr:\/bin\/bash/g" /etc/passwd- && \
-    ln -s /sbin/php-fpm7 /sbin/php-fpm
+# Install and configure Imagick
+RUN curl -fL -o imagick.tgz 'https://pecl.php.net/get/imagick-3.7.0.tgz'; \
+    echo '5a364354109029d224bcbb2e82e15b248be9b641227f45e63425c06531792d3e *imagick.tgz' | sha256sum -c -; \
+    tar --extract --directory /tmp --file imagick.tgz imagick-3.7.0; \
+    sed -i -e 's!^//#endif$!#endif!' /tmp/imagick-3.7.0/Imagick.stub.php; \
+    docker-php-ext-install /tmp/imagick-3.7.0; \
+    rm -rf imagick.tgz /tmp/imagick-3.7.0;
 
-ADD files/nginx.conf /etc/nginx/
-ADD files/php-fpm.conf /etc/php81/
-RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/bin/wp-cli && chown nginx:nginx /usr/bin/wp-cli
+# Configure PHP extensions
+RUN docker-php-ext-configure gd --with-avif --with-freetype --with-jpeg --with-webp; \
+    docker-php-ext-install -j "$(nproc)" \
+        bcmath \
+        exif \
+        gd \
+        mysqli \
+        opcache \
+        zip
 
-VOLUME ["/usr/html"]
+# Cleanup unnecessary files and verify installation
+RUN set -eux; \
+    out="$(php -r 'exit(0);')"; \
+    [ -z "$out" ]; \
+    err="$(php -r 'exit(0);' 3>&1 1>&2 2>&3)"; \
+    [ -z "$err" ]; \
+    extDir="$(php -r 'echo ini_get("extension_dir");')"; \
+    [ -d "$extDir" ]; \
+    ! { ldd "$extDir"/*.so | grep 'not found'; };
 
-# Copy data for add-on
-COPY run.sh /
-RUN chmod a+x /run.sh
-CMD [ "/run.sh" ]
+# Set recommended PHP.ini settings
+RUN { \
+    echo 'opcache.memory_consumption=128'; \
+    echo 'opcache.interned_strings_buffer=8'; \
+    echo 'opcache.max_accelerated_files=4000'; \
+    echo 'opcache.revalidate_freq=2'; \
+} > /usr/local/etc/php/conf.d/opcache-recommended.ini
+
+# Configure Apache
+RUN a2enmod rewrite expires; \
+    a2enmod remoteip; \
+    { \
+        echo 'RemoteIPHeader X-Forwarded-For'; \
+        echo 'RemoteIPInternalProxy 10.0.0.0/8'; \
+        echo 'RemoteIPInternalProxy 172.16.0.0/12'; \
+        echo 'RemoteIPInternalProxy 192.168.0.0/16'; \
+        echo 'RemoteIPInternalProxy 169.254.0.0/16'; \
+        echo 'RemoteIPInternalProxy 127.0.0.0/8'; \
+    } > /etc/apache2/conf-available/remoteip.conf; \
+    a2enconf remoteip; \
+    find /etc/apache2 -type f -name '*.conf' -exec sed -ri 's/([[:space:]]*LogFormat[[:space:]]+"[^"]*)%h([^"]*")/\1%a\2/g' '{}' +
+
+# Download and set up WordPress
+RUN set -eux; \
+    version='6.7.2'; \
+    sha1='ff727df89b694749e91e357dc2329fac620b3906'; \
+    curl -o wordpress.tar.gz -fL "https://wordpress.org/wordpress-$version.tar.gz"; \
+    echo "$sha1 *wordpress.tar.gz" | sha1sum -c -; \
+    tar -xzf wordpress.tar.gz -C /usr/src/; \
+    rm wordpress.tar.gz; \
+    chown -R www-data:www-data /usr/src/wordpress; \
+    mkdir wp-content; \
+    for dir in /usr/src/wordpress/wp-content/*/ cache; do \
+        dir="$(basename "${dir%/}")"; \
+        mkdir "wp-content/$dir"; \
+    done; \
+    chown -R www-data:www-data wp-content; \
+    chmod -R 1777 wp-content
+
+# Set up Apache and permissions
+RUN mkdir -p /var/www/html && chown -R root:root /var/www/html
+COPY --from=wordpress:latest /var/www/html /var/www/html
+RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html
+
+# Expose ports
+EXPOSE 80
+
+# Start Apache
+CMD ["httpd", "-D", "FOREGROUND"]
